### ISSUE TITLE
Pinning can result in download loop

### ISSUE THREAD

**Issue by SaintDubious** [ultrasonic/ultrasonic#416]
## Problem description

The other day I pinned a bunch of songs and left the house. In the afternoon I got a warning from my data provider that I had chewed up 9GB of data that day! Turns out ultrasonic was continually downloading one of the songs over and over and over and over.

### Steps to reproduce

Go to album view, select the check box next to a particular song, hit the little pin icon at the bottom. 

## System information

 * **Ultrasonic version**: 2.18.0 (and also develop branch)
 * **Android version**: 11 (and also emulator)
 * **Device info**: Pixel 3
 
## Additional notes

This one scares me a bit, so I think I'll take it on as my next bug fix.

**Comment by EricBrunel** [comment]
I just got this issue too and can give a few more details:

- The Subsonic "official" app suffers from the same problem. I tried both, and they both go into a loop when trying to "pin" or download the same file;
- The problem is very probably Android 11 - related: I have an older phone with Lineage OS 17.1 and downloading the very same file on it works without problem.

I checked the permissions for both apps and I made sure both had the permission to access the file system. However, I noticed that I could give the official Subsonic app the access to "all files", but this wasn't possible for Ultrasonic: the only available option was "Media". I thought I might mention that, even if it has little chance to be important for the issue, since it happens in both apps...

Hope this can help.

**Comment by SaintDubious** [comment]
Thanks for the additional info @EricBrunel . I'm also using Android 11, so perhaps that's why I ran into it myself. I just submitted a PR that doesn't actually address the download failures, but rather the problem of the infinite retries. I'd hate to think that someone out there is getting surprised by a high monthly bill due to this issue.

**Comment by SaintDubious** [comment]
In an effort to get this fix in for the next release I think we can go ahead and call it "fixed" with https://github.com/ultrasonic/ultrasonic/pull/431 . There's still some outstanding bugs that actually cause the download failure. But the important part is that we now won't try to download forever.

I'm not sure of the policy for closing issues, so I'll leave it to the maintainers to close this as they see fit.

**Comment by EricBrunel** [comment]
Has this issue been completetely fixed in 2.21.0? I tried a couple of days ago to download a set of songs with 2.20.0 and it went into a loop as it did before, but now that I've installed v2.21.0, everything seems to work fine.

**Comment by SaintDubious** [comment]
As far as I'm aware this fix should have been in 2.20.0, but there has been a lot of work on refactoring some of the backend bits, so maybe it got extra-fixed for 2.21.0? Odd question, but how long did you let the loop go? This fix was more of a band-aid, it just put in a max retry count of 5, so the loop still happened, but it wouldn't eat up all your bandwidth.

**Comment by EricBrunel** [comment]
OK, rereading my comment, I haven't been clear enough, like, at all. What I meant was: the cause for the loop in the first place was that downloads quite often failed. I had songs that consistently failed to download in v2.20.0 on Android 11, which indeed caused a loop. It wasn't an infinite loop, like it did in previous versions, but there was a download loop nonetheless.

But with v2.21.0, I no more get failed downloads, so no loops at all. Hence my question, since I haven't seen anything related to this problem in the release notes. Was it an intentional fix, or a side-effect of something else?

**Comment by nitehu** [comment]
I think it wasn't something that was fixed intentionally, with a closed issue and all. But as we migrate to kotlin and to the new media player (and other modern APIs), a lot of things got a lot straighter than they were before, so it is possible that some things are just working better now.
Ultrasonic still has some weird behavior which I currently guess are due to concurrency, e.g. playback / buffering not starting just after a delay of a few seconds, so it is entirely possible that the download fails are not yet fixed altogether, just got better - and they may even return :)
It is always a great help for us if you could check the logs on your phone and on your server after a failure (only if you have a few minutes and are tech-savvy) and post it to us, maybe we can get a clue what bugs there are still.
